# Generated by Django 5.2.3 on 2025-06-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='offline', max_length=50)),
                ('token', models.CharField(help_text='Shared secret for authentication', max_length=255)),
            ],
        ),
    ]
